{
  "name": "Jamiamanzoor",
  "compatibility_date": "2025-12-31",
  "type": "webpack", // optional if youâ€™re using Workers Sites
  "site": {
    "bucket": "./dist",
    "entry-point": "workers-site"
  }
}
